Update it.yaml
TurboWarp/translations pull request #7
Opened 2020-11-08 17:59 UTC by sfederici

Complete Italian translation

2020-11-09 03:00 UTC, GarboMuffin requested changes
This seems pretty good to me, aside from one missing period

I would like to get some feedback from other Italian speakers first before merging this, however

2020-11-09 03:00 UTC, GarboMuffin commented on languages/it.yaml
> +  message: Ci dispiace, sembra che TurboWarp sia andato in crash. Aggiorna la pagina per riprovare
missing period?

2020-11-09 08:28 UTC, sfederici commented on languages/it.yaml
> +  message: Ci dispiace, sembra che TurboWarp sia andato in crash. Aggiorna la pagina per riprovare
Yes, the final period is missing.

2020-11-09 17:43 UTC, merged

2020-11-09 17:51 UTC, sfederici commented
Excellent. When is the Italian translation expected to be available online?

2020-11-09 18:07 UTC, GarboMuffin commented
Hopefully within a few days. There's some changes that need to be made in other places to allow translations to actually be loaded

2020-11-11 04:02 UTC, GarboMuffin commented
Italian translation is live on staging (https://staging.turbowarp.org/), will be live on production probably tomorrow

2020-11-11 04:06 UTC, GarboMuffin commented
Also some more messages were added that were previously hard-coded as English. Consider submitting a pull request for those if you have time

2020-11-11 07:45 UTC, sfederici commented
> Italian translation is live on staging (https://staging.turbowarp.org/), will be live on production probably tomorrow

Excellent! Thanks!